// <auto-generated />
namespace CODEFIRST_MIGRATIONS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class primeira_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeira_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202011051141366_primeira_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
