// <auto-generated />
namespace CODEFIRST_MIGRATIONS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_novos_campos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_novos_campos));
        
        string IMigrationMetadata.Id
        {
            get { return "202011051150429_add_novos_campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
